# Traefik konfiguracja i certyfikaty *.localtest.me

configs:
  homepage-docker-config:
    content: |
      ---
      my-docker:
        socket: /var/run/docker.sock
  
  homepage-services-config:
    content: |
      ---
      # For configuration options and examples, please see:
      # https://gethomepage.dev/configs/services/
  
  homepage-settings-config:
    content: |
      ---
      providers:
        openweathermap: openweathermapapikey
        weatherapi: weatherapiapikey
  
  homepage-widgets-config:
    content: |
      ---
      - resources:
          cpu: true
          memory: true
          disk: /
  
  homepage-bookmarks-config:
    content: |
      ---
      - Narzedzia Lokalne:
          - Portainer (localhost) - Zarządzanie Dockerem:
              - abbr: PO
                icon: si-portainer
                href: http://localhost:9000/
                description: http://localhost:9000
          - Portainer - Zarządzanie Dockerem:
              - abbr: PO
                icon: si-portainer
                href: http://docker.localtest.me
                description: http://docker.localtest.me      

      - nAxiom:
          - Wersje nAxiom:
              - abbr: PO
                icon: mdi-download-box-outline
                href: https://opteam.sharepoint.com/sites/nAxiomReleases/Releases
                description: https://opteam.sharepoint.com/sites/nAxiomReleases/Releases
          - Dokumentacja nAxiom:
              - abbr: PO
                icon: mdi-book-open-blank-variant-outline
                href: https://naxiom-docs.bitbucket.io/
                description: https://naxiom-docs.bitbucket.io/
          - Nexus Developerski:
              - abbr: PO
                icon: mdi-download-network-outline
                href: http://nexus.naxiom.local
                description: http://nexus.naxiom.local
          - Nexus Produkcyjny:
              - abbr: PO
                icon: mdi-cloud-download-outline
                href: http://repo.opteam.pl
                description: http://repo.opteam.pl



services:
  mssql:
    image: mcr.microsoft.com/mssql/server:${NAX_MSSQL_VERSION-2019-latest}
    #container_name: naxiom-common-mssql
    restart: unless-stopped
    ports:
      - ${NAX_MSSQL_EXPOSED_PORT-1433}:1433
    environment:
      ACCEPT_EULA: Y
      #HOMEDIR: ${NAX_MSSQL_DATA_DIR}
      MSSQL_SA_PASSWORD: ${NAX_MSSQL_PASSWORD}
      MSSQL_COLLATION: 'Polish_CI_AS'
    networks:
      - naxiom-common-db
    volumes:
      - mssql_data:/var/opt/mssql                                           # Wolumen na bazy danych
      - ${NAX_MSSQL_DATA_DIR-/mnt/c/Docker/mssql}:/var/opt/mssql/backups    # Folder na backupy (z hosta)
    labels:
      - "homepage.group=${COMPOSE_PROJECT_NAME}"
      - "homepage.name=SQL Server"
      - "homepage.icon=si-microsoftsqlserver"
      - "homepage.href=mssql://localhost:${NAX_MSSQL_EXPOSED_PORT-1433}"
      - "homepage.description=Baza danych MS SQL Server"

  traefik:
    image: traefik:${NAX_TRAEFIK_VERSION-v3.6.7}
    #container_name: naxiom-common-traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      # HTTP
      - "80:80"
      # Dashboard
      #- "8080:8080"
    command:
      # Docker provider - połączenie do Docker daemon
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-proxy"
      
      # Entry points
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      
      # Dashboard API
      - "--api.dashboard=true"
      - "--api.insecure=true"
      
      # Logi
      - "--log.level=INFO"
      - "--accesslog=true"
      


    volumes:
      # Połączenie do Docker socket - umożliwia Traefik czytanie informacji o kontenerach
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - naxiom-common-npm
    labels:
      - "traefik.enable=true"
      # Dashboard HTTP router
      - "traefik.http.routers.traefik.rule=Host(`${NAX_TRAEFIK_DOMAIN-proxy.localtest.me}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      # Homepage labels
      - "homepage.group=${COMPOSE_PROJECT_NAME}"
      - "homepage.name=Traefik"
      - "homepage.icon=si-traefikproxy"
      - "homepage.href=https://${NAX_TRAEFIK_DOMAIN-proxy.localtest.me}"
      - "homepage.description=Reverse proxy i load balancer"

  dozzle:
    image: amir20/dozzle:${NAX_DOZZLE_VERSION-pr-4404}
    #container_name: naxiom-common-dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #ports:
    #  - "8888:8080"
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      #DOZZLE_FILTER: "name=naxiom"  # Tylko kontenery z naxiom w nazwie
    networks:
      - naxiom-common-npm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`${NAX_DOZZLE_DOMAIN-logs.localtest.me}`)"
      - "traefik.http.routers.dozzle.entrypoints=web"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      # Homepage labels
      - "homepage.group=${COMPOSE_PROJECT_NAME}"
      - "homepage.name=Dozzle"
      - "homepage.icon=mdi-text-box-multiple"
      - "homepage.href=https://${NAX_DOZZLE_DOMAIN-logs.localtest.me}"
      - "homepage.description=Podgląd logów kontenerów"

  homepage:
    image: ghcr.io/gethomepage/homepage:${NAX_HOMEPAGE_VERSION-latest}
    #container_name: naxiom-common-homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${NAX_HOMEPAGE_DOMAIN-home.localtest.me}
    #ports:
    #  - "3000:3000"
    configs:
      - source: homepage-docker-config
        target: /app/config/docker.yaml
      - source: homepage-services-config
        target: /app/config/services.yaml
      - source: homepage-settings-config
        target: /app/config/settings.yaml
      - source: homepage-widgets-config
        target: /app/config/widgets.yaml
      - source: homepage-bookmarks-config
        target: /app/config/bookmarks.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - naxiom-common-npm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`${NAX_HOMEPAGE_DOMAIN-home.localtest.me}`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      # Homepage labels
      - "homepage.group=${COMPOSE_PROJECT_NAME}"
      - "homepage.name=Homepage"
      - "homepage.icon=si-homepage"
      - "homepage.href=https://${NAX_HOMEPAGE_DOMAIN-home.localtest.me}"
      - "homepage.description=Dashboard aplikacji"


  # nginx-proxy-manager:
  #   image: 'jc21/nginx-proxy-manager:${NAX_NGINXPM_VERSION-latest}'
  #   container_name: naxiom-common-nginx-proxy-manager
  #   restart: unless-stopped
  #   ports:
  #     - '80:80' # Public HTTP Port
  #     - '443:443' # Public HTTPS Port
  #     - '${NAX_NGINXPM_ADMIN_PORT-81}:81' # Admin Web Port
  #   networks:
  #     - naxiom-common-npm
  #   environment:
  #      DISABLE_IPV6: 'true'
  #      INITIAL_ADMIN_EMAIL: 'admin@admin'
  #      INITIAL_ADMIN_PASSWORD: ''   
  #   volumes:
  #     - nginx_proxy_manager_data:/data
  #     - nginx_proxy_manager_letsencrypt:/etc/letsencrypt

  # rabbitmq:
  #   image: rabbitmq:${NAX_RABBITMQ_VERSION}-management
  #   container_name: naxiom-common-rabbitmq
  #   restart: unless-stopped
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${NAX_RABBITMQ_USERNAME}
  #     RABBITMQ_DEFAULT_PASS: ${NAX_RABBITMQ_PASSWORD}
  #   #ports:
  #     #- "${NAX_RABBITMQ_EXPOSED_PORT}:15672"
  #     #- "5672:5672"
  #   networks:
  #     - naxiom-common
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq/mnesia
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "ping"]
  #     interval: 10s
  #     timeout: 10s
  #     start_period: 8s

volumes:
  mssql_data:
      name: naxiom-common-mssql-data
  homepage_data:
      name: naxiom-common-homepage_data
      
  # rabbitmq_data:
  #     name: naxiom-common-rabbitmq-data
  # nginx_proxy_manager_data:
  #     name: naxiom-common-nginx-proxy-manager-data    
  # nginx_proxy_manager_letsencrypt:
  #     name: naxiom-common-nginx-proxy-manager-letsencrypt

networks:
  naxiom-common-db:
    name: naxiom-common-db
    driver: bridge
  naxiom-common-npm:
    name: naxiom-common-npm
    driver: bridge